name: sidekick
description: 'Sidekick.'
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Used for declarative routing
  go_router: ^14.0.0

  # Used for dependency injection
  get_it: ^8.0.2

  # Used for enhanced logging and debugging
  logger: ^2.4.0
  supabase_flutter: ^2.17.2
  flutter_secure_storage: ^11.0.0

  # Used to open the footer's Terms and Privacy links in the browser
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
